# Generated by Django 4.0.6 on 2022-07-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_confirmition_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmition_code',
        ),
    ]
