# Generated by Django 4.0.6 on 2022-07-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_confirmition_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmition_code',
        ),
    ]
