# Generated by Django 4.0.6 on 2022-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_confirmition_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmition',
            field=models.BooleanField(default=False),
        ),
    ]
