# Generated by Django 4.0.6 on 2022-07-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
