# Generated by Django 4.0.6 on 2022-07-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
            },
        ),
        migrations.CreateModel(
            name='SneakersType',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('male', models.CharField(choices=[('all', 'Все'), ('male', 'Мужские'), ('female', 'Женские')], default='Все', max_length=20)),
                ('size', models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.brand')),
                ('sneakers_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.sneakerstype')),
            ],
            options={
                'verbose_name': 'Кроссовки',
                'verbose_name_plural': 'Кроссовки',
            },
        ),
    ]
