# Generated by Django 4.0.6 on 2022-07-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
