# Generated by Django 4.0.6 on 2022-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_male_alter_product_size_commentrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '🌟'), (2, '🌟🌟'), (3, '🌟🌟🌟'), (4, '🌟🌟🌟🌟'), (5, '🌟🌟🌟🌟🌟')], null=True),
        ),
    ]
