# Generated by Django 4.0.6 on 2022-07-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_like_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
    ]
