# Generated by Django 4.0.6 on 2022-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_commentrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
